### ISSUE TITLE
"Oops! you have loaded package color after bidi package" with minted package 

### ISSUE THREAD

**Issue by seloumi** [bidi-tex/bidi#12]
## Brief outline of the issue
Adding `minted` package with `bidi` (even if it is added before) produce error
 
>  Oops! you have loaded package color after bidi package

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode
\documentclass[12pt]{article}
\usepackage{minted}
\usepackage{fontspec}
\usepackage{bidi}

\begin{document}

Test

\end{document}
```

## Log and PDF files  

[test.log](https://github.com/bidi-tex/bidi/files/3881535/test.log)

**Comment by davidcarlisle** [comment]
It may be able to avoid this warning, but the fix implied by the error message of loading `color` before `bidi` seems to work:

```
\documentclass[12pt]{article}
\usepackage{color}
\usepackage{minted}
\usepackage{fontspec}
\usepackage{bidi}

\begin{document}

Test

\end{document}
```

**Comment by seloumi** [comment]
Package `minted` add `color` package at end preamble if not loaded
```
\AtEndPreamble{%
  \@ifpackageloaded{color}{}{%
    \@ifpackageloaded{xcolor}{}{\RequirePackage{xcolor}}}%
}
```
https://github.com/gpoore/minted/blob/5d72859d714a6f2f6a42eec524476994d954b960/source/minted.sty#L48-L51
Thanks for your reply, you can close the issue, I think.
