### ISSUE TITLE
bidi uses deprecated \box_use_clear:N

### ISSUE THREAD

**Issue by u-fischer** [bidi-tex/bidi#13]
In `pdfbase-xetex-bidi.def` bidi uses in two places a deprecated expl3 command:

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode
\documentclass{article}
\usepackage{pdfbase}
\usepackage{bidi}
\begin{document}
test
\end{document}

```

gives (compiled with xelatex-dev)

~~~~
! Undefined control sequence.
<argument> \LaTeX3 error: 
                           '\box_use_clear:N' deprecated on 2019-01-01. Use ...
~~~~

The commands should be replaced by `\box_use_drop:N`.

**Comment by davidcarlisle** [comment]
fixed by b1b630ec3159a1de38270c935fec4be39320660e
