### ISSUE TITLE
Reversed parentheses in equation numbers

### ISSUE THREAD

**Issue by jspitz** [bidi-tex/bidi#5]
According to several posts on stackexchange, bidi used to correct the panthesis direction in equation via amsmath-bidi-xetex.def (see https://tex.stackexchange.com/a/144980/19291). However, this seems to be broken (see MWE below).

The workaround given at https://tex.stackexchange.com/a/186047/19291 does not seem to work either (see commented code).

```TeX
% !TEX TS-program = xelatex
\documentclass[a4paper, twoside, titlepage, 11pt]{report}
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage{polyglossia}
\setmainlanguage{hebrew}
\setotherlanguage{english}
\newfontfamily\hebrewfont[Script=Hebrew]{FreeSans}
% Uncommenting this does not help either
% See https://tex.stackexchange.com/a/186047/19291
%\csname @Latintrue\endcsname
\setmainfont{FreeSans}

\begin{document}

\begin{equation}
a=\frac{dx}{dt}
\end{equation}

\end{document}
```

Note that the direction is correct if the main language is LTR, but not if it is RTL.

**Comment by reutenauer** [comment]
The workaround that currently works is an easy variation on the fix that worked five years ago: `\csname @nonlatintrue\endcsname`.  At least it does for me, can you please test?

**Comment by jspitz** [comment]
Yes, this works around it, indeed.

**Comment by reutenauer** [comment]
Shall we define that boolean in the Polyglossia language definition files for RTL languages then?

**Comment by jspitz** [comment]
I am not sure about the correct place for the fix. luabidi does not suffer from it, so it should go in `\ifxetex`. Also it seems that the command we should use would be rather `\setnonlatin` (which sets that switch to true). Alas, this seems to be not documented at all, so I have no idea about possible effects.

**Comment by seloumi** [comment]
`\csname @nonlatintrue\endcsname`  (`\setnonlatin`) solve also polyglossia issue [#213](https://github.com/reutenauer/polyglossia/issues/213#issue-378184893) without need to redefine `\arabicnumber`
![image](https://user-images.githubusercontent.com/8249073/64119305-cfb5cf80-cd99-11e9-969d-697e44d8986f.png)

**Comment by reutenauer** [comment]
Thank you @seloumi, that’s very helpful (@jspitz that’s from `bidi-doc.pdf` in case you wonder).

**Comment by jspitz** [comment]
I see. So we should revert my fixes to reutenauer/polyglossia#213 and use `\setnonlatin` in the extras of RTL languages and `\setlatin` in the nonextras.

I am currently busy with real work, though.

**Comment by jspitz** [comment]
> I see. So we should revert my fixes to [reutenauer/polyglossia#213](https://github.com/reutenauer/polyglossia/issues/213) 

This part is done.

**Comment by jspitz** [comment]
Fixed in polyglossia with the referenced commit.

**Comment by seloumi** [comment]
This solve the issue but another problem appear with `numerals=maghrib` numbering of equation still in mashriq form !
There are also warnings  of hyphenation from latex-gloss.sty 
```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{polyglossia}
\setdefaultlanguage[numerals=maghrib]{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\tableofcontents

\section{عنوان أول}
\subsection{عنوان فرعي أول}
\subsection{عنوان فرعي ثان}
\section{عنوان ثان}

\begin{equation}
a=\frac{dx}{dt}
\end{equation}

\end{document}
```

![Capture](https://user-images.githubusercontent.com/8249073/64167157-eb2be380-ce48-11e9-806d-50af5fb7f968.JPG)
